export const RANDOMIZE_PERSONS = 'RANDOMIZE_PERSONS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';



export const VOTE_STATE = "VOTE_STATE";
export const EDITING_USERNAME = "EDITING_USERNAME";
export const DELETING_USERNAME = "DELETING_USERNAME";


// export const FETCH_IMAGE_FAILURE = 'FETCH_IMAGE_FAILURE';
// export const FETCH_IMAGE_REQUEST = 'FETCH_IMAGE_REQUEST';
// export const FETCH_IMAGE_SUCCESS = 'FETCH_IMAGE_SUCCESS';



