export const RANDOMIZE_PERSONS = "RANDOMIZE_PERSONS";
export const RANDOMIZE_PERSONS_SAGA = "RANDOMIZE_PERSONS_SAGA"; //saga

export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_START = "FETCH_USER_START"; // saga

export const FETCH_USER_SAGA = "FETCH_USER_SAGA";

export const VOTE_STATE = "VOTE_STATE";

export const VOTE_STATE_SAGA = "VOTE_STATE_SAGA";

export const EDITING_USERNAME = "EDITING_USERNAME";
export const EDITING_USERNAME_SAGA = "EDITING_USERNAME_SAGA";

export const DELETING_USERNAME = "DELETING_USERNAME";
export const DELETING_USERNAME_SAGA = "DELETING_USERNAME_SAGA";

export const RANDOMIZE_IMAGES = "RANDOMIZE_IMAGES";
export const RANDOMIZE_IMAGES_SAGA = "RANDOMIZE_IMAGES_SAGA"; //saga
